README.md

Adding Aurelio header to readme

added header

---

README.md

Adding Python versions shield to README

Adding Python versions badge

---

docs/00-introduction.ipynb
docs/01-save-load-from-file.ipynb
docs/02-dynamic-routes.ipynb
docs/03-basic-langchain-agent.ipynb
poetry.lock
pyproject.toml

Minor tweaks for next version release

fix: James/v0.0.15

---

README.md

Had a typo in README stating that there was a `LlamaCppEncoder`, there is not, there is only a `LlamaCppLLM`. This PR corrects the typo

chore: update README.md and add course

---

semantic_router/schema.py
semantic_router/utils/splitters.py
tests/unit/test_splitters.py

The response from semantic splitter would be as follows:
```python
[
DocumentSplit(
docs=["Bot: Hi how are you", "User: I am doing good"],
is_triggered=True,
triggered_score=0.27847676228550966,
),
DocumentSplit(
docs=["Bot: How is the weather?", "User: It is good here."],
is_triggered=False,
triggered_score=None,
),
]
```
Closes #122

feat: Return triggered flag in response

---

semantic_router/encoders/openai.py
semantic_router/layer.py
semantic_router/route.py
semantic_router/schema.py
tests/unit/test_layer.py
tests/unit/test_route.py

Option to set `score_threshold` for each route individually now. Also defined a class for optimising each `score_threshold` at the route-level by performing a grid search.

feat: Optimal Route-Level Score Thresholds

---

semantic_router/layer.py
tests/unit/test_layer.py

Also added list_route_names for checking current route names.

feat: Added Method for Deletion of Routes in RouteLayer

---

CONTRIBUTING.md

Created Semantic Router contribution guidelines.

docs: WIP Create CONTRIBUTING.md

---

CONTRIBUTING.md

Corrected Linting Procedure in CONTRIBUTING.md.

fix: Corrected Linting Procedure in CONTRIBUTING.md

---

semantic_router/layer.py
tests/unit/test_layer.py

fix: Added batches for large dataset training error

---

semantic_router/index/qdrant.py

fix: gRPC types import qdrant.py

---

README.md
semantic_router/index/pinecone.py

Adds source type to Pinecone client initialization

chore: add source to pinecone index

---

docs/09-route-filter.ipynb

Wrong URL notebook linked to note 09 was linked to 00 intro notebook

fix: Update 09-route-filter.ipynb

---

semantic_router/encoders/hfendpointencoder.py

**Description PR**
Added support for HF encoders that have "sentence-embeddings" as a task.
**How to use**
To use them you need the _URL endpoint_ of the running model and the related _User Access Tokens_

Added HFEncoderEndpoint

---

docs/00-introduction.ipynb
pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the version number of the `semantic-router` package across multiple files to 0.0.36.
- In the Jupyter notebook documentation, the installation command was modified to remove specific version pinning, promoting the use of the latest version.
- Adjusted the Python version used in the Jupyter notebook metadata to reflect a downgrade from 3.12.2 to 3.11.5.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Update package version in __init__.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

chore: v0.0.36 release

---

pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the version number in `semantic_router/__init__.py` and `pyproject.toml` from 0.0.39 to 0.0.40.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Update Package Version in __init__.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the version number from 0.0.39 to 0.0.40.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/279/files#diff-9a89e6fb4fa9a2b99c426bb373fe763e29faa5a2536f081a565ae62a00059afa">+1/-1</a>&nb …

chore: v0.0.40 release

---

poetry.lock
pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the version constraints for multiple dependencies in `pyproject.toml` to allow for more flexible version ranges, ensuring better compatibility with future updates.
- This change affects key dependencies such as `openai`, `cohere`, and `tiktoken`, among others, transitioning from strict version pinning to more accommodating version intervals.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Update Dependency Version Constraints in pyproject.toml</code>&nbsp; &nbsp; </dd></summary>
<hr>
pyproject.toml
<li>Updated dependency constraints for <code>openai</code>, <code>cohere</code>, …

fix: tiktoken dep

---

pyproject.toml
semantic_router/__init__.py
semantic_router/encoders/openai.py

Enhancement
___
- Updated the project version from "0.0.43" to "0.0.44" in `__init__.py` and `pyproject.toml`.
- Corrected model configuration keys in `openai.py` to ensure proper naming conventions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Bump version number in `__init__.py`.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the `__version__` attribute from "0.0.43" to "0.0.44".
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/296/files#d …

chore: update version

---

semantic_router/index/qdrant.py

Adds support for async queries in `QdrantIndex`.

feat: QdrantIndex async query support

---

pyproject.toml

for #337
___
enhancement, other
___
- Updated the project version in `pyproject.toml` from `0.0.48` to `0.0.49`.
- Added a `license` field in `pyproject.toml` to specify the license file.
___
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Update version and add license information</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pyproject.toml
<li>Updated project version from <code>0.0.48</code> to <code>0.0.49</code>.<br> <li> Added <code>license</code> field pointing to the <code>LICENSE</code> file.<br>
</details>
</td>
<td><a …

chore: add license to pyproject

---

README.md

A long time ago I asked about `ollama` code samples : 
- https://github.com/aurelio-labs/semantic-router/issues/117
This PR shows-up what could be achieved thanks to semantic-router in a real life case. Therefore, here are some gifts for you : 
- **:scroll: A public Kaggle** Notebook : [🔀 Semantic Router: ollama/gemma2 hotline](https://www.kaggle.com/code/adriensales/semantic-router-ollama-gemma2-hotline/notebook)
- **:memo: A dedicated article on DEV.to** : [🔀 Semantic Router w. ollama/gemma2 : real life 10ms hotline challenge 🤯](https://dev.to/adriens/semantic-router-w-ollamagemma2-real-life-10ms-hotline-challenge-1i3f)
- **:popcorn:  A youtube** video : [🔀 Semantic Router w. ollama/gemma2 : "CCaaS" real life hotline usecase](https://www.youtube.com/watch?v=QHqti5NprX8)
Thank you for …

feat: 🎁 🔀 Semantic Router ollama/gemma2 hotline

---

pyproject.toml
semantic_router/index/base.py
semantic_router/index/pinecone.py

Enhancement, Configuration changes
___
- Added `init_async_index` parameter to `BaseIndex` class.
- Added `init_async_index` parameter to Pinecone index initialization.
- Conditional initialization of `async_client` based on `init_async_index`.
- Bumped version from 0.0.51 to 0.0.52 in `pyproject.toml`.
___
<tr>
<td>
<details>
<summary><strong>base.py</strong><dd><code>Add `init_async_index` parameter to `BaseIndex` class</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/index/base.py
- Added `init_async_index` parameter to `BaseIndex` class.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/352/files#d …

feat: add init_async_index param

---

docs/indexes/pinecone_async.ipynb

Documentation, Enhancement
___
- Updated the `semantic-router[pinecone]` package version from 0.0.47 to 0.0.52 in the Pinecone async documentation.
- Enhanced the `PineconeIndex` initialization by adding the `init_async_index=True` parameter to support asynchronous index initialization.
___
<tr>
<td>
<details>
<summary><strong>pinecone_async.ipynb</strong><dd><code>Update Pinecone async documentation with latest package version and </code><br><code>async index initialization</code></dd></summary>
<hr>
docs/indexes/pinecone_async.ipynb
<li>Updated <code>semantic-router[pinecone]</code> package version from 0.0.47 to <br>0.0.52.<br> <li> Added …

fix: docs outdated

---

semantic_router/index/base.py
semantic_router/index/local.py
semantic_router/index/pinecone.py
semantic_router/index/qdrant.py
semantic_router/layer.py

Related to Issue#361.
This PR updates the logic for embedding local routes to reduce unnecessary costs associated with embedding operations. The previous approach embedded all passed local utterances a priori and then synced with Pinecone. This often resulted in embedding utterances that were not ultimately added to the index, incurring avoidable costs.
**Changes Implemented**
- Modified the embedding process to occur conditionally based on the selected syncing logic.
- Ensured that only the utterances which will be added to the index are embedded.
- Removed the prior step of embedding all local utterances before syncing.
**Testing**
- Verified that only necessary utterances are embedded during the syncing process.
- Ensured compatibility and functionality with the existing Pinecone …

feat: Optimize sync embeddings

---

semantic_router/encoders/vit.py
tests/unit/encoders/test_vit.py

Bug fix, Tests
___
- Updated error messages in `VitEncoder` to correctly reference the encoder and provide clear installation instructions.
- Refactored unit tests for `VitEncoder` to use `unittest.mock.patch` for simulating import errors and added assertions to verify error messages.
___
<tr>
<td>
<details>
<summary><strong>vit.py</strong><dd><code>Update error messages for import exceptions in VitEncoder</code></dd></summary>
<hr>
semantic_router/encoders/vit.py
<li>Updated error messages to refer to <code>VitEncoder</code> instead of <br><code>HuggingFaceEncoder</code>.<br> <li> Improved clarity of installation instructions in error messages.<br> …

fix: tests and errors messages

---

docs/source/conf.py
pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the project release version in the Sphinx documentation configuration to 0.0.62.
- Updated the `__version__` attribute in `semantic_router/__init__.py` to 0.0.62.
- Updated the version in `pyproject.toml` to 0.0.62.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update project release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from 0.0.61 to 0.0.62.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/404/files#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a51698">+1/-1</a>&nbs …

chore: release v0.0.62

---

docs/source/conf.py
pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the project release version in the documentation configuration file to 0.0.63.
- Updated the `__version__` variable in `semantic_router/__init__.py` to 0.0.63.
- Updated the version in `pyproject.toml` to 0.0.63 for project configuration.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update project release version in documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from 0.0.62 to 0.0.63.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/409/files#diff-008dcb3426febd …

chore: release v0.0.63

---

docs/source/conf.py
pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the release version in `conf.py` for Sphinx documentation from 0.0.64 to 0.0.65.
- Updated the package version in `__init__.py` from 0.0.64 to 0.0.65.
- Updated the version in `pyproject.toml` from 0.0.64 to 0.0.65.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update project release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from 0.0.64 to 0.0.65.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/417/files#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a51698">+1/-1</a>&nbs …

chore: release v0.0.65

---

poetry.lock
pyproject.toml
semantic_router/encoders/cohere.py

Address https://github.com/cohere-ai/cohere-python/issues/584

fix: cohere types

---

docs/source/conf.py
poetry.lock
pyproject.toml
semantic_router/__init__.py

enhancement, dependencies
___
- Updated the project version from `0.0.68` to `0.0.69` across multiple files, indicating a new release.
- Modified the Pinecone dependency in `pyproject.toml` from `pinecone-client` to `pinecone` with a version constraint of `<5.0.0`.
- Adjusted documentation configuration to reflect the new release version.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update documentation configuration for new release version</code></dd></summary>
<hr>
- Updated the release version from `0.0.68` to `0.0.69`.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/440/file …

fix: update to allow latest pinecone versions

---

docs/source/conf.py
pyproject.toml
semantic_router/__init__.py

enhancement
___
- Updated the release version in `conf.py` for Sphinx documentation from `0.0.69` to `0.0.70`.
- Updated the `__version__` attribute in `__init__.py` to `0.0.70`.
- Updated the package version in `pyproject.toml` to `0.0.70`.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from `0.0.69` to `0.0.70`.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/442/files#diff-008dcb3426febd76778 …

chore: version fix

---

docs/source/conf.py
pyproject.toml
semantic_router/__init__.py

enhancement, documentation
___
- Updated the release version in the Sphinx documentation configuration file to `0.0.71`.
- Updated the `__version__` attribute in the `semantic_router` package's `__init__.py` file to `0.0.71`.
- Updated the package version in `pyproject.toml` to `0.0.71`.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from `0.0.70` to `0.0.71`.
</details>
</td>
<td><a …

chore: release v0.0.71

---

docs/source/conf.py
poetry.lock
pyproject.toml
semantic_router/__init__.py
semantic_router/encoders/cohere.py
semantic_router/llms/cohere.py
tests/unit/encoders/test_cohere.py
tests/unit/llms/test_llm_cohere.py

enhancement, dependencies
___
- Refactored `CohereEncoder` and `CohereLLM` to make the `cohere` dependency optional, using `PrivateAttr` for the client and adding `_initialize_client` methods.
- Updated error handling to raise informative messages if the `cohere` package is not installed.
- Modified `pyproject.toml` to mark `cohere` as an optional dependency and added it to the optional dependencies group.
___
<tr>
<td>
<details>
<summary><strong>cohere.py</strong><dd><code>Refactor CohereEncoder to use optional cohere dependency</code>&nbsp; </dd></summary>
<hr>
semantic_router/encoders/cohere.py
<li>Made the <code>cohere</code> dependency optional by …

feat: move cohere to optional dep

---

.github/workflows/test.yml

enhancement
___
- Updated the GitHub Actions workflow to include testing for Python 3.12.
- Removed testing for Python 3.9 from the workflow.
___
<tr>
<td>
<details>
<summary><strong>test.yml</strong><dd><code>Update Python versions in GitHub Actions test matrix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/test.yml
<li>Removed Python 3.9 from the test matrix.<br> <li> Added Python 3.12 to the test matrix.<br>
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/456/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …

feat: add test for 3.12 and remove 3.9

---

semantic_router/index/base.py
semantic_router/index/pinecone.py
semantic_router/routers/base.py
semantic_router/schema.py
tests/unit/test_sync.py

Enhancement, Tests
___
- Introduced a locking mechanism for index operations to prevent concurrent modifications.
- Enhanced `_read_config` and `_write_config` methods for better configuration handling and logging.
- Integrated locking into `sync`, `_write_hash`, and `delete` methods to ensure safe operations.
- Refactored `ConfigParameter` to replace `namespace` with `scope` and updated timestamp handling.
- Added comprehensive unit tests to validate sync lock functionality, including error handling and automatic lock release.
___
<tr>
<td>
<details>
<summary><strong>base.py</strong><dd><code>Add index locking mechanism and enhance configuration …

feat: add sync lock

---

docs/02-dynamic-routes.ipynb

The explanation had a small typo on it.

fixed typo on dynamic routes doc

---

.github/workflows/test.yml
docs/00-introduction.ipynb
docs/01-save-load-from-file.ipynb
docs/02-dynamic-routes.ipynb
docs/03-basic-langchain-agent.ipynb
docs/06-threshold-optimization.ipynb
docs/08-async-dynamic-routes.ipynb
docs/09-route-filter.ipynb
docs/indexes/local.ipynb
docs/indexes/pinecone-local.ipynb
docs/indexes/pinecone-sync-routes.ipynb
docs/indexes/pinecone.ipynb
docs/indexes/pinecone_async.ipynb
docs/user-guide/features/dynamic-routes.md
docs/user-guide/features/threshold-optimization.md
docs/user-guide/guides/migration-to-v1.md
pyproject.toml
semantic_router/tokenizers.py
uv.lock

This pull request includes updates to the dependencies and workflow configurations, as well as improvements to the tokenization process. The most important changes are grouped by theme below.
* Updated the `semantic-router` dependency to version `0.1.5` in multiple documentation files to ensure consistency and compatibility. [[1]](diffhunk://#diff-21491e5b61c76430cdaa72c7efd5fe297e3128ea10845545e116fe59ff0e4056L56-R56) [[2]](diffhunk://#diff-bcaf55d491fe6c62c97670b731954a68ac9d482426f0ecc1cbcd204ba152c5a7L49-R49) [[3]](diffhunk://#diff-7529b220ddfe1fafa0482c1ddaabb4b5eab6fe63fd2d4d8d025d1b20a0ac1975L98-R98) [[4]](diffhunk://#diff-83a381ab07178ac33ee397e8981fa3a802302e86ef22794bb94f88498d25f55cL55-R55) [[5]](diffhunk://#diff-5ce7ddabf718d1bbd04d64c3997d4711c6eea20ec9e816ac69f0c780c84a7ba0L4 …

fix: dep issue
