- poetry.lock
- pyproject.toml
- semantic_router/encoders/__init__.py
- semantic_router/encoders/fastembed.py
- tests/unit/encoders/test_fastembed.py
Closes #67 
Lmk if there are more tests that should be added or any documentation that would help.
> feat: Add fastembed encoder

- semantic_router/encoders/base.py
- semantic_router/encoders/bm25.py
- semantic_router/encoders/cohere.py
- semantic_router/encoders/fastembed.py
- semantic_router/encoders/openai.py
- semantic_router/hybrid_layer.py
- semantic_router/layer.py
- tests/unit/encoders/test_base.py
- tests/unit/test_hybrid_layer.py
- tests/unit/test_layer.py
Default `score_threshold` values has been moved to encoders. Now, it's possible to specify a custom `score_threshold` during encoder initialization, which will be utilized by the `RouteLayer` and `HybridRouteLayer`.
Closes #70
> feat: Move score_threshold to encoders

- README.md
- docs/05-local-execution.ipynb
- semantic_router/llms/__init__.py
- tests/unit/llms/test_llm_llamacpp.py
Importing any LLM from `semantic_router.llms` will cause a `ModuleNotFoundError` when `semantic-router` is not installed with the `local` extra.
Fix this by removing the import of `LlamaCppLLM` from the `__init__.py` file. End users will have to import `LlamaCppLLM` from `semantic_router.llms.llamacpp` instead.
> fix: Fixes ModuleNotFoundError

- semantic_router/encoders/cohere.py
- semantic_router/encoders/fastembed.py
- semantic_router/encoders/openai.py
- semantic_router/encoders/zure.py
- semantic_router/llms/cohere.py
- semantic_router/llms/openai.py
- semantic_router/llms/openrouter.py
- semantic_router/utils/llm.py
this PR uses the **raise from** idiom in order to wrap caught exceptions with additional context while preserving their original stack traces.
The original issue required the exception in [semantic-router/semantic_router/llms/openai.py](https://github.com/aurelio-labs/semantic-router/blob/f8fcd43a7018d6216668250ff99d9acbe7f16789/semantic_router/llms/openai.py#L53) be re-raised, but this PR addresses similar occurrences of this pattern while preserving the additional context added by the new raised exceptions.
> fix: issue #94 raise from exceptions

- poetry.lock
- pyproject.toml
- semantic_router/encoders/base.py
- semantic_router/encoders/fastembed.py
- semantic_router/encoders/huggingface.py
- semantic_router/llms/base.py
- semantic_router/route.py
- semantic_router/schema.py
- semantic_router/utils/function_call.py
- tests/unit/test_schema.py
For this, I followed this [Pydantic Migration Guide](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features) and it showed me a quick and easy way to temporarily (though probably not best practice) to allow me and others to use pydantic 2+ with semantic router.
It passes all tests so I assume it would work well while we wait for a more official pydantic v2 migration.
Lmk what you all think.
> feat: Allow Pydantic V2+

- README.md
- semantic_router/llms/zure.py
the __call__ method of the Zure class to make it more informative
Issue #94
> fix: issue #94 added from clause to the exception statement in

- semantic_router/encoders/openai.py
- tests/unit/encoders/test_openai.py
Adding support for `OPENAI_ORGANIZATION` when initialising the `OpenAIEncoder`.
This PR includes:
- The code changes to support this feature
- Minor updates to the unit tests to ensure this functionality works as expected
> feat: openai encoder org id support

- docs/examples/unstructured-element-splitter.ipynb
Example of how we can use a Rolling window splitter with Unstructured library.
- Partition file using Unstructured
- Group elements by title (Exclude invalid titles)
- Create chunks from Unstructured elements using the semantic splitter
- Visualize the text
Example notebook:
`docs/examples/unstructured-element-splitter.ipynb`
> feat: Unstructured elements splitting example

- semantic_router/encoders/zure.py
Added missing .self to class init.
Fixes Issue #188
> fix: fixes #188 ```AzureOpenAIEncoder``` issue

- semantic_router/llms/llamacpp.py
Closes #206 .
A bug was introduced in #190 that overwrote the kwarg value of `LlamaCppLLM.llm`, replacing a passed kwarg instance of `llama_cpp.Llama`.
The same bug also replaced the passed value of `LlamaCppLLM.grammar`.
Rely on `self._llama_cpp.{Llama,LlamaGrammar}` if we need these classes, remove the overriding of `llm` and `grammar` from the values passed as kwargs.
> fix: kwarg LlamaCppLLM.llm overwritten by import

- semantic_router/splitters/rolling_window.py
It was missing the check for max_split_tokens for the current + next block of text
> fix: Hard split for max token size

- .github/workflows/test.yml
- semantic_router/encoders/base.py
- semantic_router/index/base.py
- semantic_router/index/pinecone.py
- semantic_router/layer.py
- semantic_router/splitters/rolling_window.py
- tests/unit/test_layer.py
fix: BadRequestError: Error code: 400 - {'error': {'message': "'$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Occurs when _encode_documents attempts to run splitter(docs), and len(docs)>2048, as it's an OpenAI limit when generating embeddings of an array.
How it fixes the problem:
Split the array into multiple arrays when len(docs)>2000, and sends the multiple arrays to generate the embeddings.
> fix: Added fix to encode documents within rolling window

- pyproject.toml
- semantic_router/__init__.py
- semantic_router/encoders/openai.py
enhancement, bug_fix
___
- Updated the version of the semantic-router package to 0.0.37 in both __init__.py and pyproject.toml.
- Enhanced the text encoding in `semantic_router/encoders/openai.py` by replacing the `encode` method with `encode_ordinary` for faster processing without disallowed special tokens.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Update package version in __init__.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the version number from …
> fix: James/encoder disallowed special

- docs/00-introduction.ipynb
- semantic_router/encoders/openai.py
- semantic_router/schema.py
Encountered an issue with consecutive similarity functionality due to variations in file types, specifically observed with non-string data types. This pull request addresses the problem by implementing support for dynamic data types, ensuring compatibility beyond just strings.
___
Bug fix, Enhancement
___
- Enhanced `DocumentSplit` model in `semantic_router/schema.py` to support lists containing various data types, not just strings.
- Updated `content` property method to handle non-string list elements gracefully by converting them to empty strings during concatenation.
- Modified Jupyter Notebook `docs/00-introduction.ipynb` to reflect new logging outputs and updated execution counts.
- Added error outputs in the notebook regarding tqdm and IPython version warnings.
___ …
> fix: video splitter -> type error

- semantic_router/index/pinecone.py
bug_fix
___
- The PR adds a condition to include the `namespace` in the request parameters for the `_get_all` method in the Pinecone router. This ensures that the namespace is considered when fetching all vectors.
___
<tr>
<td>
<details>
<summary><strong>pinecone.py</strong><dd><code>Include Namespace in API Request Parameters</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/index/pinecone.py
<li>Added a condition to include <code>namespace</code> in the request parameters if it <br>is set.
</details>
</td>
<td><a …
> fix: add namespace to get all for pinecone

- semantic_router/index/pinecone.py
Enhancement, Bug fix
___
- Introduced an instance attribute `api_key` in `PineconeIndex` to handle API keys more effectively.
- Constructor now sets `api_key` with a direct assignment, allowing explicit passing of the key, and falls back to the environment variable if not provided.
- Added error handling to raise a `ValueError` if `api_key` is not set, ensuring the API key's presence is validated during object initialization.
- Refactored the `_get_all` method to utilize the instance's `api_key`, improving security by avoiding direct environment variable access.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
<tr>
<td>
<details>
<summary><strong>pinecone.py</strong><dd><code>Enhance API Key …
> fix: Use 'api_key' parameter if passed explicitly

- docs/encoders/bedrock.ipynb
- pyproject.toml
- semantic_router/__init__.py
enhancement
___
- Updated the version number in `semantic_router/__init__.py` and `pyproject.toml` to `0.0.41`.
- Adjusted the installation guide in `docs/encoders/bedrock.ipynb` to be version-agnostic and reflect the new version support.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Update package version in __init__.py</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the version number from `0.0.40` to `0.0.41`.
</details>
</td>
<td><a …
> chore: v0.0.41 release

- semantic_router/encoders/zure.py
- semantic_router/llms/zure.py
Added `dimension` param to Azure Encoder
Following Openai encoder changes: [link](https://github.com/aurelio-labs/semantic-router/pull/126/files#diff-957e3e71dd8cd9c500e3984ad73ff930491a9c39abed9f0ba931a1a3571fc2fc)
> feat: `AzureOpenAIEncoder` dimension support

- .github/workflows/test.yml
- README.md
- poetry.lock
- pyproject.toml
- semantic_router/encoders/zure.py
- tests/unit/encoders/test_clip.py
- tests/unit/encoders/test_huggingface.py
- tests/unit/encoders/test_vit.py
documentation
___
- Added a reference to the Arxiv paper titled "Semantic Routing for Enhanced Performance of LLM-Assisted Intent-Based 5G Core Network Management and Orchestration" by Dimitrios Manias, Ali Chouman, and Abdallah Shami to the README.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add Arxiv paper reference to README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Added a new reference to an Arxiv paper related to semantic routing.<br>
</details>
</td>
<td><a …
> feat: add dims to Azure encoder

- poetry.lock
- pyproject.toml
- semantic_router/encoders/bedrock.py
- tests/unit/encoders/test_bedrock.py
Bug fix, Enhancement, Tests, Documentation
___
- Fixed environment variable names for AWS credentials in `BedrockEncoder`.
- Added retry logic for handling expired tokens in `BedrockEncoder`.
- Refactored chunking logic into a separate method in `BedrockEncoder`.
- Improved error handling and logging in `BedrockEncoder`.
- Added comprehensive tests for `BedrockEncoder`, including retry logic, chunking functionality, and various initialization scenarios.
- Updated dependencies to include `botocore` in `pyproject.toml`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>bedrock.py</strong><dd><code>Fix and enhance BedrockEncoder initialization and API …
> feat: bedrock encoder merge

- tests/unit/encoders/test_clip.py
- tests/unit/encoders/test_huggingface.py
- tests/unit/test_layer.py
Bug fix, Tests
___
- Added `pytest.mark.skipif` to conditionally skip tests in `test_clip.py` based on the `RUN_HF_TESTS` environment variable.
- Added `pytest.mark.skipif` to conditionally skip tests in `test_huggingface.py` based on the `RUN_HF_TESTS` environment variable.
- Added `pytest.mark.skipif` to conditionally skip Pinecone-related tests in `test_layer.py` based on the `PINECONE_API_KEY` environment variable.
- Moved encoder initialization inside test functions to ensure proper setup.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
<tr>
<td>
<details>
<summary><strong>test_clip.py</strong><dd><code>Add conditional skipping for CLIP encoder tests based on environment …
> fix: update tests

- tests/unit/encoders/test_vit.py
Bug fix, Tests
___
- Added `pytest.mark.skipif` decorator to multiple test functions in `test_vit.py` to conditionally skip tests based on the `RUN_HF_TESTS` environment variable.
- This change ensures that certain tests are only run when the `RUN_HF_TESTS` environment variable is set, preventing unnecessary test execution in environments where these tests are not required.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
<tr>
<td>
<details>
<summary><strong>test_vit.py</strong><dd><code>Add conditional skip for ViT encoder tests based on environment </code><br><code>variable</code></dd></summary>
<hr>
tests/unit/encoders/test_vit.py
<li>Added <code>os</code> import.<br> <li> Added …
> fix: add skip to vit

- tests/integration/encoders/test_openai_integration.py
- tests/unit/test_layer.py
Bug fix, Tests
___
- Added `pytest.mark.skipif` decorators to skip OpenAI encoder tests if `OPENAI_API_KEY` is not set.
- Added conditional checks to Pinecone tests to ensure they only run if `PINECONE_API_KEY` is set.
- Modified test logic in Pinecone tests to handle cases where the index class is not Pinecone.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
<tr>
<td>
<details>
<summary><strong>test_openai_integration.py</strong><dd><code>Add skips to OpenAI encoder tests based on API key presence</code></dd></summary>
<hr>
tests/integration/encoders/test_openai_integration.py
<li>Added <code>pytest.mark.skipif</code> decorators to skip tests if <code>OPENAI_API_KEY</code> is <br>not set.<br> <li> …
> fix: add skips to pinecone openai tests

- tests/integration/encoders/test_openai_integration.py
Bug fix, Tests
___
- Added a condition to the `openai_encoder` fixture to return a `BaseEncoder` instance if the `OPENAI_API_KEY` environment variable is not set.
- This change ensures that tests do not fail when the `OPENAI_API_KEY` is missing.
- Added import for `BaseEncoder` in the test file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>test_openai_integration.py</strong><dd><code>Add condition to initialize OpenAI encoder based on API key.</code></dd></summary>
<hr>
tests/integration/encoders/test_openai_integration.py
<li>Added import for <code>BaseEncoder</code>.<br> <li> Modified <code>openai_encoder</code> fixture to return <code>BaseEncoder</code> if …
> fix: add condition to init encoder

- pyproject.toml
- semantic_router/layer.py
- tests/unit/test_layer.py
Bug fix, Enhancement
___
- Modified the `delete` method in `semantic_router/layer.py` to handle non-existent routes more permissively by logging a warning instead of raising a `ValueError` and ensuring the index is updated.
- Updated the project version in `pyproject.toml` from `0.0.47` to `0.0.48`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>layer.py</strong><dd><code>Modify route deletion logic to be more permissive</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/layer.py
<li>Changed error handling for non-existent routes in the <code>delete</code> method.<br> <li> Replaced <code>ValueError</code> with a …
> fix: more permissive deletes

- pyproject.toml
- semantic_router/__init__.py
Enhancement, Documentation
___
- Updated the `__version__` in `semantic_router/__init__.py` from "0.0.46" to "0.0.50".
- Updated the project version in `pyproject.toml` from "0.0.49" to "0.0.50".
- Changed the license in `pyproject.toml` from a file reference to "MIT".
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Bump version in `__init__.py` to 0.0.50</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the `__version__` from "0.0.46" to "0.0.50".
</details>
</td>
<td><a …
> chore: update versions and fix license

- pyproject.toml
- semantic_router/index/base.py
- semantic_router/index/local.py
- semantic_router/index/pinecone.py
- semantic_router/index/qdrant.py
- semantic_router/layer.py
New implementation at startup to synchronize the local index with the remote index based on the specified mode.
Modes:
- `error`: Raise an error if local and remote are not synchronized.
- `remote`: Take remote as the source of truth and update local to align.
- `local`: Take local as the source of truth and update remote to align.
- `merge-force-remote`: Merge both local and remote taking only remote routes utterances when a route with same route name is present both locally and remotely.
- `merge-force-local`: Merge both local and remote taking only local routes utterances when a route with same route name is present both locally and remotely.
- `merge`: Merge both local and remote, merging also local and remote utterances when a route with same route name is present both locally and …
> feat: add sync setting parameter to index

- pyproject.toml
- semantic_router/__init__.py
- semantic_router/index/local.py
- semantic_router/index/pinecone.py
Enhancement, Bug fix
___
- Added `aquery` method to `local.py` for asynchronous querying with route filtering and error handling.
- Enhanced `query` and `aquery` methods in `pinecone.py` to support `sparse_vector` parameter.
- Updated `_async_query` method in `pinecone.py` to handle `sparse_vector`.
- Included `kwargs` in `pinecone.py` methods to pass additional parameters.
___
<tr>
<td>
<details>
<summary><strong>local.py</strong><dd><code>Add asynchronous query method with route filtering</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/index/local.py
<li>Added <code>aquery</code> method for asynchronous …
> feat: add sparse vector for PineconeIndex

- semantic_router/index/base.py
- semantic_router/layer.py
Related to Issue#374. Introduced an option .fit(local_execution=True) during training to move training to a local index then move back to the remote one.
This can be tested with a simple code like the following:
```
from semantic_router import Route
politics = Route(
name="politics",
utterances=[
"isn't politics the best thing ever",
"why don't you tell me about your political opinions",
"don't you just love the president" "don't you just hate the president",
"they're going to destroy this country!",
"they will save the country!",
],
)
chitchat = Route(
name="chitchat",
utterances=[
"Did you watch the game last night?",
"what's your favorite type of music?",
"Have you read any good books lately?",
"nice weather we're having",
"Do you have any plans for the weekend?",
],
)
mathematics = …
```
> feat: Added local execution for layer fitting

- docs/source/conf.py
- poetry.lock
- pyproject.toml
- semantic_router/__init__.py
Bug fix, Enhancement
___
- Updated the release version in `docs/source/conf.py` from `0.0.57` to `0.0.58`.
- Updated the package version in `semantic_router/__init__.py` from `0.0.57` to `0.0.58`.
- Updated the package version in `pyproject.toml` from `0.0.57` to `0.0.58`.
- Made `psycopg2` an optional dependency in `pyproject.toml`.
- Corrected the `postgres` extra in `pyproject.toml` to use `psycopg2`.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update documentation release version to 0.0.58</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the …
> fix: most postgres installs to optional

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
- semantic_router/utils/function_call.py
- tests/unit/test_function_schema.py
Addresses #383 
Enhancement, Tests
___
- Introduced `Parameter` class to represent function parameters with attributes like name, description, type, default value, and required status.
- Added `FunctionSchema` class to generate schemas for functions, including methods to convert these schemas to Ollama format.
- Implemented `_ollama_type_mapping` method to map Python types to Ollama types.
- Added unit tests to validate the functionality of `FunctionSchema` and its Ollama conversion.
___
<tr>
<td>
<details>
<summary><strong>function_call.py</strong><dd><code>Add `Parameter` and `FunctionSchema` classes with Ollama conversion</code></dd></summary>
<hr> …
> feat: add ollama signature builder

- semantic_router/encoders/openai.py
- semantic_router/encoders/zure.py
- semantic_router/utils/function_call.py
- tests/integration/encoders/test_openai_integration.py
- tests/unit/encoders/test_azure.py
- tests/unit/encoders/test_openai.py
This update introduces a `max_retries` option for the `OpenAIEncoder` and `AzureOpenAIEncoder` classes. This option allows users to specify the maximum number of retry attempts for API calls in case of errors. By default, it is set to 3 retries. If no retries are needed, you can set `max_retries` to 0.
```python
from semantic_router.encoders import OpenAIEncoder
encoder = OpenAIEncoder(name="text-embedding-3-large", max_retries=2)
```
___
enhancement
___
- Introduced a `max_retries` option for both `OpenAIEncoder` and `AzureOpenAIEncoder` classes, allowing users to specify the maximum number of retry attempts for API calls.
- Implemented exponential backoff retry logic for handling API call failures in both synchronous and asynchronous methods.
- Enhanced error logging to provide more …
> feat: add max_retries to OpenAI and Azure encoders

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
enhancement
___
- Updated the project release version in the Sphinx documentation configuration file to `0.0.60`.
- Updated the `__version__` attribute in the `__init__.py` file to `0.0.60`.
- Updated the package version in `pyproject.toml` to `0.0.60`.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update project release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from `0.0.59` to `0.0.60`.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/390/files#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a5169 …
> chore: v0.0.60

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
- semantic_router/index/base.py
- semantic_router/index/local.py
- semantic_router/index/pinecone.py
- semantic_router/index/postgres.py
- semantic_router/index/qdrant.py
- tests/unit/encoders/test_vit.py
Fixes issue #396
___
enhancement
___
- Introduced an abstract `aget_routes` method in the base index class to be implemented by subclasses.
- Implemented the `aget_routes` method in the Pinecone index to asynchronously retrieve route and utterance objects.
- Added error logging for the `aget_routes` method in LocalIndex, PostgresIndex, and QdrantIndex to indicate it is not implemented.
- Added helper methods in PineconeIndex for asynchronous data retrieval and metadata fetching.
___
<tr>
<td>
<details>
<summary><strong>base.py</strong><dd><code>Introduce abstract `aget_routes` method in base index class</code></dd></summary>
<hr> …
> feat: Implemented aget_routes async method for pinecone index

- semantic_router/index/pinecone.py
Related to issue #393 
Now able to delete routes at startup with sync setting enabled when using a namespace
___
enhancement, bug fix
___
- Added a `namespace` argument to the `delete` method in the `_remove_and_sync` function to ensure that routes are deleted with the correct namespace.
- This change addresses the issue where routes could not be deleted at startup when the sync setting was enabled and a namespace was used.
___
<tr>
<td>
<details>
<summary><strong>pinecone.py</strong><dd><code>Add namespace argument to route deletion in Pinecone index</code></dd></summary>
<hr>
semantic_router/index/pinecone.py
<li>Added <code>namespace</code> argument to …
> fix: namespace in sync routes deletion

- semantic_router/index/pinecone.py
Uses `pinecone.Index.list` to fetch vector ids, this has the benefit of using Pinecone's handling of Index host, especially when using the pinecone mock server
___
enhancement
___
- Replaced the manual pagination and request handling for retrieving vector IDs with the `pinecone.Index.list` method, simplifying the code and leveraging Pinecone's built-in functionality.
- Removed unnecessary parameters and headers setup for requests, as they are now handled by the Pinecone library.
- Streamlined the process of fetching metadata associated with vector IDs.
___
<tr>
<td>
<details>
<summary><strong>pinecone.py</strong><dd><code>Simplify vector ID retrieval …
> feat: Use Pinecone library list functionality

- .github/workflows/docs.yml
- docs/source/requirements.txt
enhancement, documentation
___
- Introduced a new GitHub Actions workflow file to automate the building of documentation.
- The workflow is triggered on pull requests and runs on the latest Ubuntu environment.
- It sets up a Python environment using Poetry and installs necessary dependencies.
- The documentation is built using Sphinx, with caching implemented for Poetry to improve efficiency.
___
<tr>
<td>
<details>
<summary><strong>docs.yml</strong><dd><code>Add GitHub Actions workflow for documentation build</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/docs.yml
<li>Added a new GitHub Actions workflow for …
> feat: add docs workflow file

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
- semantic_router/index/pinecone.py
Bug fix, Documentation, Other
___
- Fixed a bug in the `pinecone.py` file by ensuring `sr_function_schema` is accessed safely using `data.get`.
- Updated the version number to 0.0.64 across multiple files including `conf.py`, `__init__.py`, and `pyproject.toml`.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update documentation release version to 0.0.64</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from 0.0.63 to 0.0.64.
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/415/files#diff-008dcb3426 …
> fix: bug in pinecone index for func schema

- Makefile
- semantic_router/index/pinecone.py
- semantic_router/layer.py
- tests/unit/test_layer.py
- Fixed and introduced pinecone index tests
- Introduced sync tests
- Minor fixes
___
Bug fix, Tests
___
- Improved synchronization logic in `pinecone.py` by adding checks for empty `function_schemas` and setting them to `None` if empty.
- Enhanced error handling in `layer.py` by adding try-except blocks for route deletion and adjusting dimensions handling.
- Added new test cases in `test_layer.py` to verify Pinecone index synchronization and introduced time delays to ensure index population.
- Updated existing tests to include metadata checks and improved test reliability with Pinecone index.
___
<tr>
<td>
<details> …
> fix: Fixed pinecone tests

- README.md
- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
enhancement, documentation
___
- Updated the version from 0.0.65 to 0.0.66 across multiple files, including `conf.py`, `__init__.py`, and `pyproject.toml`.
- Added a link to the documentation in the `README.md`.
- Simplified the authors list in `pyproject.toml` to a single entry.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from 0.0.65 to 0.0.66.
</details>
</td>
<td><a …
> chore: v0.0.66

- poetry.lock
- pyproject.toml
- semantic_router/encoders/cohere.py
Bug fix
___
- Fixed the import statement for `EmbeddingsByTypeEmbedResponse` in `cohere.py`.
- Updated the type check to use the correct class `EmbeddingsByTypeEmbedResponse` instead of `EmbedResponse_EmbeddingsByType`.
___
<tr>
<td>
<details>
<summary><strong>cohere.py</strong><dd><code>Fix import and type check for Cohere embeddings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/encoders/cohere.py
<li>Fixed import statement for <code>EmbeddingsByTypeEmbedResponse</code>.<br> <li> Updated type check from <code>EmbedResponse_EmbeddingsByType</code> to …
> fix: cohere type

- semantic_router/layer.py
- tests/unit/test_layer.py
Based on point 1 from this issue: https://github.com/aurelio-labs/semantic-router/issues/392
At the moment just altering the `RouteLayer` method `update` to allow the user to update the `Route` `score_thresholds` that are held in memory. 
Later we'll build functionality to allow for thresholds to persist remotely (e.g. in Pinecone), and to update them remotely too.
We'll also implement alteration of `utterances` for `Routes` later.
___
enhancement, error handling
___
- Enhanced the `update` method in `RouteLayer` to allow updating the `score_threshold` of a route directly.
- Added error handling to raise a `ValueError` if neither `threshold` nor `utterances` are provided.
- Implemented a check to raise a `KeyError` if the specified route does not exist.
- Added logging to track changes in …
> feat: Update route thresholds manually

- poetry.lock
- pyproject.toml
dependencies
___
- Updated the `pinecone` dependency version in `pyproject.toml` to ensure compatibility with versions 5.0.0 and above.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Update `pinecone` dependency version in `pyproject.toml`</code>&nbsp; </dd></summary>
<hr>
pyproject.toml
<li>Updated the <code>pinecone</code> dependency version to be greater than or equal to <br>5.0.0.<br>
</details>
</td>
<td><a href="https://github.com/aurelio-labs/semantic-router/pull/441/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> fix: pinecone version

- docs/source/route_layer/sync.rst
- semantic_router/index/base.py
- semantic_router/index/pinecone.py
- semantic_router/layer.py
Related to issue #443 
Added is_synced method in Pinecone index and route layer that is checking if local and remote index are currently synced and return True if so, otherwise it returns False.
___
enhancement
___
- Introduced `is_synced` method in the base index class to check synchronization between local and remote indexes.
- Implemented `is_synced` method in the Pinecone index to compare local and remote data, ensuring they are synchronized.
- Refactored the synchronization logic to improve code clarity and maintainability.
- Added logging to provide insights into the synchronization process by displaying local and remote dictionaries.
- Enhanced the route layer with an `is_synced` method to verify synchronization status, raising an error if the index is not set to sync.
___ …
> feat: is_synced method for Pinecone Index

- .github/workflows/test.yml
configuration changes
___
- Removed the duplicate testing trigger for push events to the main branch in the GitHub Actions workflow configuration.
- Ensured that testing is still triggered on pull requests to maintain CI/CD integrity.
___
<tr>
<td>
<details>
<summary><strong>test.yml</strong><dd><code>Remove duplicate testing trigger on push events</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/test.yml
<li>Removed duplicate testing trigger on push to the main branch.<br> <li> Retained testing trigger on pull requests.<br>
</details>
</td>
<td><a …
> fix: remote duplicate testing on pr merge

- docs/indexes/pinecone-sync-routes.ipynb
- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
- semantic_router/layer.py
- semantic_router/schema.py
- tests/unit/test_sync.py
Bug fix
___
- Fixed the function schemas handling in `from_tuple` method by ensuring `function_schemas` is a list, even if initially provided as a dictionary.
- Updated the sync strategy method call to use `get_sync_strategy` with the `sync_mode` parameter in `sync` method.
___
<tr>
<td>
<details>
<summary><strong>layer.py</strong><dd><code>Update sync strategy method call with parameter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/layer.py
<li>Changed method call from <code>to_sync_strategy</code> to <code>get_sync_strategy</code> with <br><code>sync_mode</code> parameter.<br>
</details> …
> fix: function schemas

- semantic_router/schema.py
- tests/unit/test_sync.py
Bug fix
___
- Fixed an issue with inconsistent ordering in function schemas and metadata by sorting them before stringification.
- Ensured accurate comparison of stringified function schemas and metadata by using sorted keys.
___
<tr>
<td>
<details>
<summary><strong>schema.py</strong><dd><code>Sort function schemas and metadata for consistent diffs</code>&nbsp; &nbsp; </dd></summary>
<hr>
semantic_router/schema.py
<li>Added sorting for <code>function_schemas</code> and <code>metadata</code> using <code>json.dumps</code> with <br><code>sort_keys=True</code>.<br> <li> Ensured consistent order for stringified function schemas and metadata <br>for accurate …
> fix: sort func schemas and metadata in diffs

- docs/00-introduction.ipynb
- docs/examples/hybrid-router.ipynb
- docs/indexes/pinecone-sync-routes.ipynb
- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
enhancement, documentation
___
- Updated the project version from `0.1.0.dev2` to `0.1.0.dev3` across multiple files, including configuration and documentation.
- Modified installation commands in Jupyter Notebooks to reflect the new version.
- Changed references from `RouteLayer` to `Router` in the introduction notebook, updating import statements and usage examples.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update release version in Sphinx configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the release version from …
> chore: new dev release

- docs/00-introduction.ipynb
documentation
___
- Updated the introductory documentation in `docs/00-introduction.ipynb` to include the missing `auto_sync` parameter in the `SemanticRouter` instantiation example.
- Ensures the example code is accurate and aligns with the expected usage of the `SemanticRouter` class.
___
<tr>
<td>
<details>
<summary><strong>00-introduction.ipynb</strong><dd><code>Add `auto_sync` parameter to `SemanticRouter` example in introduction</code></dd></summary>
<hr>
docs/00-introduction.ipynb
<li>Added the <code>auto_sync</code> parameter to the <code>SemanticRouter</code> instantiation <br>example.<br> <li> Updated the introductory documentation to include …
> fix: missing auto_sync in intro doc

- semantic_router/encoders/bedrock.py
Adds support for multimodal embeddings (TEXT, IMAGE or both) via [Amazon Titan for Multimodal Embeddings](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-titan-embed-mm.html) (Titan MM) and model-specific inference parameters via `model_kwargs`. Notice that Titan MM expects a base64-encoded image.
**Example:**
```python
"""
Semantic Router powered by Amazon Titan Multimodal Embeddings
https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-titan-embed-mm.html
"""
import base64
from datasets import load_dataset
from semantic_router.encoders import BedrockEncoder
data = load_dataset("aurelio-ai/shrek-detection", split="train", trust_remote_code=True)
data = data.to_list()
def process_image(example):
"""Turns images into base64-encoded strings."""
im_bytes …
```
> feat: Bedrock Multimodal Embeddings 💬🖼️

- tests/unit/test_router.py
Tests
___
- Added a new pytest fixture `route_single_utterance` to provide a single route with one utterance for testing purposes.
- Implemented a new test `test_initialization_single_utterance` to verify the behavior of `SemanticRouter` when initialized with a single utterance route.
- The test ensures the correct score threshold is set and validates the number of utterances in the index.
- Included a conditional sleep for PineconeIndex to allow index updates during the test.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>test_router.py</strong><dd><code>Add test for single route with single utterance</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat: add test for single route single utterance

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
- semantic_router/routers/base.py
- semantic_router/routers/hybrid.py
- semantic_router/routers/semantic.py
- tests/unit/test_router.py
`np.squeeze` was converting the vector into a 1d array when there is only a single utterance leading to errors.
___
Bug fix
___
- Fixed an issue where `np.squeeze` was causing dimensionality problems by converting vectors into 1D arrays in single utterance scenarios.
- Replaced `np.array(vector)` with `vector[0]` in route retrieval methods to handle vectors correctly.
- Removed unnecessary use of `np.squeeze` in encoding methods to simplify the process and avoid errors.
___
<tr>
<td>
<details>
<summary><strong>base.py</strong><dd><code>Fix vector handling in route retrieval methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: vector shape for single utterance

- semantic_router/index/pinecone.py
Fixed missing namespace param inside the request for getting all routes asynchronously with PineconeIndex
___
Bug fix
___
- Fixed an issue where the `namespace` parameter was missing in the `_async_fetch_metadata` method of the Pinecone integration.
- Added logic to include the `namespace` parameter in the request if it is defined.
___
<tr>
<td>
<details>
<summary><strong>pinecone.py</strong><dd><code>Fix missing `namespace` parameter in `_async_fetch_metadata` method</code></dd></summary>
<hr>
semantic_router/index/pinecone.py
<li>Added a check for <code>self.namespace</code> in the <code>_async_fetch_metadata</code> method.<br> <li> Included the …
> fix: Fixed namespace missing in _async_fetch_metadata inside Pinecone

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
enhancement
___
- Updated the `release` version in the Sphinx documentation configuration file (`conf.py`) to `0.1.0.dev5`.
- Updated the `__version__` variable in `semantic_router/__init__.py` to `0.1.0.dev5`.
- Updated the `version` field in `pyproject.toml` to `0.1.0.dev5`.
- These changes collectively upgrade the project version to `0.1.0.dev5`.
___
<tr>
<td>
<details>
<summary><strong>conf.py</strong><dd><code>Update Sphinx documentation configuration for new release version</code></dd></summary>
<hr>
- Updated the `release` variable from `0.1.0.dev4` to `0.1.0.dev5`.
</details>
</td>
<td><a …
> chore: upgrade to dev5

- semantic_router/encoders/base.py
- semantic_router/index/base.py
- semantic_router/index/local.py
- semantic_router/index/postgres.py
- semantic_router/llms/base.py
- semantic_router/route.py
- semantic_router/routers/base.py
- semantic_router/schema.py
- semantic_router/utils/function_call.py
Fixes the following warning from Pydantic:
```
PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.1.1/migration/
warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
```
> refactor: fix pydantic warning by switching from config

- docs/source/conf.py
- pyproject.toml
- semantic_router/__init__.py
- semantic_router/encoders/__init__.py
- semantic_router/encoders/azure_openai.py
- tests/unit/encoders/test_azure.py
- uv.lock
This pull request includes several updates and improvements to the `semantic-router` project, including version updates, file renaming, and enhancements to the `AzureOpenAIEncoder` class. The most important changes include updating the project version, renaming and refactoring the `AzureOpenAIEncoder`, and updating related tests.
* Updated the project version to `0.1.1` in `docs/source/conf.py`, `pyproject.toml`, and `semantic_router/__init__.py`. [[1]](diffhunk://#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a51698L18-R18) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L3-R3) [[3]](diffhunk://#diff-9a89e6fb4fa9a2b99c426bb373fe763e29faa5a2536f081a565ae62a00059afaL6-R6)
* Renamed `semantic_router/encoders/zure.py` to …
> feat: Azure OpenAI AD Authentication and Custom HTTP Client

- docs/encoders/bedrock.ipynb
- docs/encoders/vision-transformer.ipynb
- docs/examples/ollama-local-execution.ipynb
- docs/get-started/quickstart.md
- docs/indexes/pinecone-async.ipynb
- docs/indexes/postgres/postgres.ipynb
- docs/indexes/qdrant.ipynb
Refactor RouteLayer to SemanticRouter across all documentation and examples.
Each notebook now uses the SemanticRouter structure consistently.
- Documentation
- Updated all references from RouteLayer to SemanticRouter in multiple notebooks.
- Adjusted import statements to reflect new SemanticRouter structure.
> docs(notebook): Refactor RouteLayer to SemanticRouter across documentation and examples

- semantic_router/routers/base.py
- semantic_router/routers/hybrid.py
- tests/unit/test_router.py
This PR will resolve https://github.com/aurelio-labs/semantic-router/issues/586, https://github.com/aurelio-labs/semantic-router/issues/593, and https://github.com/aurelio-labs/semantic-router/issues/589
This pull request enhances the functionality of the `semantic_router` module by introducing asynchronous methods, improving error handling, and adding test coverage for new and existing features. The most significant changes include the addition of an asynchronous `acall` method to the `HybridRouter` class, support for a `limit` parameter in routing methods, and improved test cases to validate these updates.
* **Asynchronous Routing Method**: Added an `acall` method to the `HybridRouter` class, enabling asynchronous routing with support for both dense and sparse vectors. This includes …
> fix: add limit to acall and fix async hybrid router

- .env.example
- semantic_router/index/pinecone.py
- semantic_router/routers/base.py
- tests/unit/test_router.py
Running `PineconeIndex`'s `_init_async_index` was not working for me for the following reasons:
1. API returning boolean, but code checking for string literal `"true"`
2. `self.index` stays `None`, short-circuiting all the async operations.
3. `self.host` is not being set, deviating from the synchronous method counterpart.
To address these, this PR includes:
- Set `self.index` to prevent short circuit on async calls when `self.index` is `None`.
- Make sure to always set `self.host` to match the behavior of the synchronous initialization method.
- Always return `index_stats` if index exists or was created (previously `None` was returned for an existing index).
> fix: pinecone.py async initialization

- semantic_router/route.py
- Don't throw an exception when LLM doesn't return tool call arguments gracefully by returning the route name without the `function_call` attribute
Fixes #506
> fix: handle llm not returning function call gracefully
